Repository Eppie-io/Eppie-App, pull requests merged in 2024-10, with the labels that each got.

#360 chore: move files to Eppie.App.Shared
  source/Eppie.App/Eppie.App.Shared/Common/UITools.cs
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.Shared/IncrementalLoading/IncrementalLoadingCollection.cs
  source/Eppie.App/Eppie.App.Shared/Tools/ElementHierarchyTools.cs
  source/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  source/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: platform/all, type/chore

#364 chore: move Services and Models to Eppie.App.Shared
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.Shared/Models/BrandLoader.cs
  source/Eppie.App/Eppie.App.Shared/Models/NotificationManager.cs
  source/Eppie.App/Eppie.App.Shared/Services/DispatcherService.cs
  source/Eppie.App/Eppie.App.Shared/Services/ErrorHandler.cs
  source/Eppie.App/Eppie.App.Shared/Services/FilePickerService.cs
  source/Eppie.App/Eppie.App.Shared/Services/LauncherService.cs
  source/Eppie.App/Eppie.App.Shared/Services/LocalSettingsService.cs
  source/Eppie.App/Eppie.App.Shared/Services/LocalizationService.cs
  source/Eppie.App/Eppie.App.Shared/Services/MessageService.UWP.cs
  source/Eppie.App/Eppie.App.Shared/Services/MessageService.Uno.cs
  source/Eppie.App/Eppie.App.Shared/Services/MessageService.cs
  source/Eppie.App/Eppie.App.Shared/Services/NavigationService.cs
  source/Eppie.App/Eppie.App.Shared/Services/NotificationService.cs
  source/Eppie.App/Eppie.App.UWP/App.xaml.cs
  source/Eppie.App/Eppie.App/App.xaml.cs
Labels: platform/all, type/chore

#363 ci: fix build workflow
  .github/configurations/build.json
  .github/workflows/build.yml
Labels: platform/all, type/ci

#365 chore: move Helpers to Eppie.App.Shared
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.Shared/Helpers/BitmapTools.cs
Labels: platform/all, type/chore

#366 chore: move Converters to Eppie.App.Shared
  source/Eppie.App/Eppie.App.Shared/Converters/BitmapSourceConverters.cs
  source/Eppie.App/Eppie.App.Shared/Converters/TuviMailConvertersDictionary.xaml
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
Labels: platform/all, type/chore

#368 chore: move App.xaml to Eppie.App.Shared
  source/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs
  source/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs
  source/Eppie.App/Eppie.App.Shared/App.xaml
  source/Eppie.App/Eppie.App.Shared/App.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.Shared/Services/MessageService.UWP.cs
  source/Eppie.App/Eppie.App.Shared/Services/MessageService.Uno.cs
  source/Eppie.App/Eppie.App.Shared/Services/MessageService.cs
  source/Eppie.App/Eppie.App.UWP/App.xaml
  source/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  source/Eppie.App/Eppie.App/App.xaml
  source/Eppie.App/Eppie.App/Platforms/Android/Main.Android.cs
  source/Eppie.App/Eppie.App/Platforms/Desktop/Program.cs
  source/Eppie.App/Eppie.App/Platforms/MacCatalyst/Main.maccatalyst.cs
  source/Eppie.App/Eppie.App/Platforms/WebAssembly/Program.cs
  source/Eppie.App/Eppie.App/Platforms/iOS/Main.iOS.cs
Labels: platform/all, type/chore

#369 chore: move Extensions to Eppie.App.Shared
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.Shared/Extensions/AttachedCommands.cs
  source/Eppie.App/Eppie.App.Shared/Extensions/HyperlinkExtension.cs
  source/Eppie.App/Eppie.App.Shared/Extensions/TextDocumentExtension.cs
  source/Eppie.App/Eppie.App.Shared/Extensions/WebViewExtension.cs
Labels: platform/all, type/chore

#373 chore: move Behaviors to Eppie.App.Shared
  source/Eppie.App/Directory.Packages.props
  source/Eppie.App/Eppie.App.Shared/Behaviors/ClipboardBehaviorBase.cs
  source/Eppie.App/Eppie.App.Shared/Behaviors/CopyToClipboardBehavior.cs
  source/Eppie.App/Eppie.App.Shared/Behaviors/DialogBehavior.cs
  source/Eppie.App/Eppie.App.Shared/Behaviors/FileBehavior.cs
  source/Eppie.App/Eppie.App.Shared/Behaviors/ItemClickCommandBehavior.cs
  source/Eppie.App/Eppie.App.Shared/Behaviors/ListViewItemClickBehavior.cs
  source/Eppie.App/Eppie.App.Shared/Behaviors/ObjectToFileBehavior.cs
  source/Eppie.App/Eppie.App.Shared/Behaviors/PasteFromClipboardBehavior.cs
  source/Eppie.App/Eppie.App.Shared/Behaviors/TreeViewItemInvokeBehavior.cs
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  source/Eppie.App/Eppie.App/Eppie.App.csproj
  src/Eppie.App/Eppie.App.Shared/Behaviors/DialogBehavior.cs
Labels: platform/all, type/chore

#376 build: update Uno.Sdk
  source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.Uno/global.json
  source/Eppie.App/global.json
Labels: platform/all, type/build

#380 chore: move Controls to Eppie.App.Shared
  source/Eppie.App/Directory.Packages.props
  source/Eppie.App/Eppie.App.Shared/Controls/AccountSettingsControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/AccountSettingsControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/AttachmentListControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/AttachmentListControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/BaseUserControl.cs
  source/Eppie.App/Eppie.App.Shared/Controls/ContactsListControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/ContactsListControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/DecentralizedAccountSettingsControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/DecentralizedAccountSettingsControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/EmailProvidersListControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/EmailProvidersListControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/EmailsInputControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/EmailsInputControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/ErrorControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/ErrorControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/LanguageSelectionControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/LanguageSelectionControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/MailBoxesListControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/MailBoxesListControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/MessageListControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/MessageListControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/NavPanelTabControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/NavPanelTabControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/PasswordControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/PasswordControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/PromptTextInputControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/PromptTextInputControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/ProtonAccountSettingsControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/ProtonAccountSettingsControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Controls/RichTextEditor.cs
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  source/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: platform/all, type/chore

#381 chore: move Views to Eppie.App.Shared
  source/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs
  source/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs
  source/Eppie.App/Eppie.App.Shared/App.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.Shared/Views/AboutPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/AboutPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/AllMessagesPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/AllMessagesPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/BasePage.cs
  source/Eppie.App/Eppie.App.Shared/Views/ContactMessagesPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/ContactMessagesPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/DecentralizedAccountSettingsPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/DecentralizedAccountSettingsPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/FolderMessagesPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/FolderMessagesPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/IdentityManagerPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/IdentityManagerPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/PasswordPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/PasswordPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/PgpKeyPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/PgpKeyPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/PgpKeysPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/PgpKeysPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/ProtonAccountSettingsPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/ProtonAccountSettingsPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/SelectEmailProviderPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/SelectEmailProviderPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/WelcomePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/WelcomePage.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml.cs
Labels: platform/all, type/chore

#385 chore: move Styles to Eppie.App.Shared
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.Shared/Styles/NavigationViewStyle.xaml
  source/Eppie.App/Eppie.App.Shared/Styles/TuviMailStyles.xaml
Labels: platform/all, type/chore

#386 feat: add the UWP app launch
  source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.UWP/Eppie.App.Converters.UWP.csproj
  source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.Uno/Eppie.App.Converters.Uno.csproj
  source/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs
  source/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs
  source/Eppie.App/Eppie.App.Shared/App.xaml
  source/Eppie.App/Eppie.App.Shared/App.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.Uno.cs
  source/Eppie.App/Eppie.App.Shared/Behaviors/TreeViewItemInvokeBehavior.cs
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
Labels: platform/all, type/chore

#388 fix: fix TreeView behavior
  source/Eppie.App/Eppie.App.Shared/Behaviors/TreeViewItemInvokeBehavior.cs
Labels: platform/uwp, type/fix, ignore-for-release

#389 style: format the xaml files
  source/Eppie.App/Eppie.App.Shared/App.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/AccountSettingsControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/AttachmentListControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/ContactsListControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/DecentralizedAccountSettingsControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/EmailProvidersListControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/EmailsInputControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/ErrorControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/LanguageSelectionControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/MailBoxesListControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/MessageListControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/NavPanelTabControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/PasswordControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/PromptTextInputControl.xaml
  source/Eppie.App/Eppie.App.Shared/Controls/ProtonAccountSettingsControl.xaml
  source/Eppie.App/Eppie.App.Shared/Converters/TuviMailConvertersDictionary.xaml
  source/Eppie.App/Eppie.App.Shared/StaticResources/StaticStringResources.xaml
  source/Eppie.App/Eppie.App.Shared/Styles/NavigationViewStyle.xaml
  source/Eppie.App/Eppie.App.Shared/Styles/TuviMailStyles.xaml
  source/Eppie.App/Eppie.App.Shared/Views/AboutPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/AllMessagesPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/ContactMessagesPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/DecentralizedAccountSettingsPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/FolderMessagesPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/IdentityManagerPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/PasswordPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/PgpKeyPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/PgpKeysPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/ProtonAccountSettingsPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/SelectEmailProviderPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/WelcomePage.xaml
Labels: platform/all, type/style

#390 chore: change xaml indent rule
  source/Eppie.App/.editorconfig
Labels: platform/all, type/chore

#392 fix: replace NavigationView control
  source/Eppie.App/Eppie.App.Shared/Behaviors/ItemClickCommandBehavior.cs
  source/Eppie.App/Eppie.App.Shared/Styles/NavigationViewStyle.xaml
  source/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml.cs
Labels: platform/all, type/fix, ignore-for-release

#393 chore: app information was added
  source/Eppie.App/Eppie.App.UWP/Package.appxmanifest
  source/Eppie.App/Eppie.App.UWP/Properties/AssemblyInfo.cs
  source/Eppie.App/Eppie.App/Package.appxmanifest
Labels: platform/all, type/chore

#394 refactor: add Eppie.App.UI.* projects
  .gitignore
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.shproj
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Properties/AssemblyInfo.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Properties/Eppie.App.UI.UWP.rd.xml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json
  source/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  source/Eppie.App/Eppie.App.sln
  source/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: platform/all, type/refactor

#396 refactor: move Converters to Eppie.App.UI
  .gitignore
  source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.Shared/Eppie.App.Converters.Shared.projitems
  source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.Shared/Eppie.App.Converters.Shared.shproj
  source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.UWP/Eppie.App.Converters.UWP.csproj
  source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.UWP/Properties/AssemblyInfo.cs
  source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.UWP/Properties/Eppie.App.Converters.UWP.rd.xml
  source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.Uno/Eppie.App.Converters.Uno.csproj
  source/Eppie.App/Eppie.App.Converters/Eppie.App.Converters.Uno/global.json
  source/Eppie.App/Eppie.App.Shared/App.xaml
  source/Eppie.App/Eppie.App.Shared/Converters/TuviMailConvertersDictionary.xaml
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/BitmapSourceConverters.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/BoolToValueConverter.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/ConverterChain.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/ConvertersDictionary.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/StringConverters.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/TimeConverters.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/ValueToBoolConverter.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/VisibilityConverters.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj
  source/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  source/Eppie.App/Eppie.App.sln
  source/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: platform/all, type/refactor

#397 feat: add a support development button
  source/Eppie.App/Eppie.App.Shared/Resources/Strings/en/Resources.resw
  source/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml
  source/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs
Labels: kind/enhancement, platform/all

#398 feat: implement SupportDevelopmentAsync() function
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.Shared/Services/PurchaseService.cs
  source/Eppie.App/Eppie.App.Shared/Views/BasePage.cs
  source/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs
  source/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs
  source/Eppie.App/Eppie.App.ViewModels/Services/IPurchaseService.cs
Labels: kind/task, platform/all

#399 build: add IDE0055 formatting rule
  source/Eppie.App/.editorconfig
Labels: platform/all, type/build

#400 refactor: move Extensions to Eppie.App.UI
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/AttachedCommands.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/HyperlinkExtension.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/TextDocumentExtension.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/WebViewExtension.cs
Labels: platform/all, type/refactor

#401 refactor: code cleaning
  source/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.cs
  source/Eppie.App/Eppie.App.Shared/Controls/EmailProvidersListControl.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml.cs
  source/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/ValueToBoolConverter.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/TextDocumentExtension.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Properties/AssemblyInfo.cs
  source/Eppie.App/Eppie.App.ViewModels/AboutPageViewModel.cs
  source/Eppie.App/Eppie.App.ViewModels/Services/ILocalSettingsService.cs
  source/Eppie.App/Eppie.App/GlobalUsings.cs
  source/Eppie.App/Eppie.App/Platforms/Android/Main.Android.cs
  source/Eppie.App/Eppie.App/Platforms/Android/MainActivity.Android.cs
Labels: platform/all, type/refactor
