Repository Eppie-io/Eppie-App, pull requests merged in 2024-11, with the labels that each got.

#403 refactor: move Behaviors to Eppie.App.UI
  source/Eppie.App/Eppie.App.Shared/Behaviors/FileBehavior.cs
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/ClipboardBehaviorBase.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/CopyToClipboardBehavior.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/DialogBehavior.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/FileBehavior.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/ItemClickCommandBehavior.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/ListViewItemClickBehavior.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/ObjectToFileBehavior.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/PasteFromClipboardBehavior.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/TreeViewItemInvokeBehavior.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj
  source/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  source/Eppie.App/Eppie.App.sln
Labels: platform/all, type/refactor

#404 refactor: move Controls to Eppie.App.UI
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AccountSettingsControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AccountSettingsControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AttachmentListControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AttachmentListControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/BaseUserControl.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/ContactsListControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/ContactsListControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/DecentralizedAccountSettingsControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/DecentralizedAccountSettingsControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailProvidersListControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailProvidersListControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailsInputControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailsInputControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/ErrorControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/ErrorControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/LanguageSelectionControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/LanguageSelectionControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MailBoxesListControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MailBoxesListControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageListControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageListControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NavPanelTabControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NavPanelTabControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/PasswordControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/PasswordControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/PromptTextInputControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/PromptTextInputControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/ProtonAccountSettingsControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/ProtonAccountSettingsControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/RichTextEditor.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj
Labels: platform/all, type/refactor

#406 refactor: move UI tools to Eppie.App.UI
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Tools/ElementHierarchyTools.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Tools/IncrementalLoadingCollection.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Tools/UITools.cs
Labels: platform/all, type/refactor

#408 feat: create MessageControl
  source/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/MessageControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/MessageControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj
Labels: platform/all, type/feature, ignore-for-release

#409 feat: create EditMessageControl
  source/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EditMessageControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/EditMessageControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/RichTextEditor.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/EditMessageControl.xaml
Labels: platform/all, type/feature, ignore-for-release

#410 feat: change EmailsInputControl
  source/Eppie.App/Directory.Packages.props
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailsInputControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/EmailsInputControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/EmailsInputControl.xaml
  source/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
Labels: platform/all, type/feature, ignore-for-release

#414 refactor: move resw files to Eppie.App.Resources library
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Eppie.App.Resources.Shared.projitems
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/af/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/ar/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/be/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/ca/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/cs/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/da/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/de/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/el/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/es/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/et/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/fi/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/fr/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/he/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/hu/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/it/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/ja/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/ko/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/lv/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/nl/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/no/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/pl/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/pt-BR/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/pt/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/ro/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/ru/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/sr-Cyrl/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/sv/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/tr/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/uk/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/vi/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/zh-CN/Resources.resw
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/zh-TW/Resources.resw
  source/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
Labels: platform/all, type/refactor, ignore-for-release

#415 fix: fix loading of string resources in code
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Eppie.App.Resources.Shared.projitems
  source/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/StringProvider.cs
  source/Eppie.App/Eppie.App.Shared/Models/NotificationManager.cs
  source/Eppie.App/Eppie.App.Shared/Services/LocalizationService.cs
  source/Eppie.App/Eppie.App.Shared/Services/MessageService.cs
  source/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/LanguageSelectionControl.xaml.cs
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/BoolToValueConverter.cs
Labels: platform/all, type/fix, ignore-for-release

#416 fix: correct x:Uid keys
  source/Eppie.App/Eppie.App.Shared/Views/AboutPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/AllMessagesPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/ContactMessagesPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/DecentralizedAccountSettingsPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/FolderMessagesPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/IdentityManagerPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/PasswordPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/PgpKeyPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/PgpKeysPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/ProtonAccountSettingsPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/SelectEmailProviderPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml
  source/Eppie.App/Eppie.App.Shared/Views/WelcomePage.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AccountSettingsControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/ContactsListControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/DecentralizedAccountSettingsControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageListControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NavPanelTabControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/PasswordControl.xaml
  source/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/ProtonAccountSettingsControl.xaml
Labels: platform/all, type/fix, ignore-for-release

#418 fix: add resources to manifest
  source/Eppie.App/Eppie.App.UWP/Package.appxmanifest
  source/Eppie.App/Eppie.App/Package.appxmanifest
Labels: platform/all, type/fix, ignore-for-release

#419 chore: merge branch 'main' into feature/296-upgrading-to-uno-platform-5
  .github/workflows/build.yml
  .github/workflows/codeql.yml
Labels: platform/all, type/chore, ignore-for-release

#420 ci: remove unused triggers
  .github/workflows/build.yml
  .github/workflows/format.yml
Labels: platform/all, ignore-for-release, type/ci

#424 test: add tests
  .gitignore
  src/Eppie.App/Eppie.App.sln
  src/Tests/Eppie.App.ViewModels.Tests/ContactComparerTests.cs
  src/Tests/Eppie.App.ViewModels.Tests/Eppie.App.ViewModels.Tests.csproj
Labels: platform/all, type/test, ignore-for-release

#431 feat: add Microsoft Engagement Framework
  src/Eppie.App/Directory.Packages.props
  src/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs
  src/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
Labels: platform/uwp, type/feature

#440 build(deps): update Uno SDK
  src/Eppie.App/Directory.Packages.props
  src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Uno/Eppie.App.Resources.Uno.csproj
  src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Uno/global.json
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  src/Eppie.App/Eppie.App/Eppie.App.csproj
  src/Eppie.App/global.json
Labels: platform/all, type/build

#443 feat: add DispatcherService
  src/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs
  src/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs
  src/Eppie.App/Eppie.App.Shared/App.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.Uno.cs
  src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  src/Eppie.App/Eppie.App.Shared/Services/ErrorHandler.cs
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  src/Eppie.App/Eppie.App.UWP/Services/DispatcherService.cs
  src/Eppie.App/Eppie.App/Services/DispatcherService.cs
Labels: platform/all, type/feature, ignore-for-release

#449 ci: fix CI build
  .github/actions/install-prerequisites/action.yml
  .github/configurations/build.json
  .github/configurations/workload.json
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/format.yml
  src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Uno/Eppie.App.Resources.Uno.csproj
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj
  src/Eppie.App/Eppie.App/Eppie.App.csproj
  src/Eppie.App/global.json
Labels: platform/all, type/ci

#451 ci: change build script
  .github/workflows/build.yml
Labels: platform/all, type/ci

#455 build: fix build
  src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
Labels: platform/all, type/build

#456 refactor: improve error handling
  src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml.cs
  src/Eppie.App/Eppie.App.ViewModels/AllMessagesPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/ContactMessagesPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/FolderMessagesPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/IdentityManagerPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MessagesViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/NewMessagePageViewModel.cs
Labels: platform/all, type/refactor

#458 fix: fix update draft message
  src/Eppie.App/Eppie.App.ViewModels/NewMessagePageViewModel.cs
Labels: platform/all, type/fix

#460 refactor: add exception info
  src/Eppie.App/Eppie.App.Shared/Services/MessageService.cs
Labels: platform/all, type/refactor
