Repository Eppie-io/Eppie-App, pull requests merged in 2024-12, with the labels that each got.

#462 refactor: add error handling
  src/Eppie.App/Eppie.Authorization.OAuth2/TokenRefresher.cs
Labels: platform/all, type/refactor

#467 feat(lang): add Chinese simplified
  src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/zh-CN/Resources.resw
Labels: platform/all, type/localization, area/localization

#472 fix: fix outlook login
  src/Eppie.App/Directory.Packages.props
  src/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.cs
  src/Eppie.App/Eppie.App.Shared/Services/MessageService.cs
  src/Eppie.App/Eppie.App.ViewModels/AccountSettingsPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Eppie.App.ViewModels.csproj
  src/Eppie.App/Eppie.App.ViewModels/Extensions/CredentialExtension.cs
  src/Eppie.App/Eppie.Authorization.OAuth2/TokenRefresher.cs
Labels: platform/all, type/fix

#475 fix: fix strings
  src/Eppie.App/Eppie.App.Resources/Eppie.App.Resources.Shared/Strings/zh-CN/Resources.resw
Labels: platform/all, area/localization

#477 fix: fix accounts update
  src/Eppie.App/Eppie.App.ViewModels/BaseAccountSettingsPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Models/MailBoxesModel.cs
Labels: platform/all, type/fix
