Repository Eppie-io/Eppie-App, pull requests merged in 2025-10, with the labels that each got.

#888 fix: fix application name not displayed in About page and Email Settings
  src/Eppie.App/Eppie.App.Shared/Views/AboutPage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailSettingsControl.xaml
Labels: platform/all, type/fix

#893 refactor: improve text clarity and consistency
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/en/Controls.resw
Labels: platform/all, type/localization

#897 ci: update snap package publication
  .github/workflows/publish-desktop-snap.yml
  packages/snap/snapcraft.template.yaml
Labels: platform/desktop, type/ci

#896 fix: fix typos in README.md
  README.md
Labels: area/docs, platform/irrelevant

#899 feat: add "Join Waiting List" button functionality
  src/Eppie.App/Eppie.App.Shared/Views/BitcoinAddressSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/EppieAddressSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/EthereumAddressSettingsPage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressSettingsView.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressSettingsView.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/en/Controls.resw
  src/Eppie.App/Eppie.App.ViewModels/SelectServicePageViewModel.cs
Labels: platform/all, type/feature
