Repository Eppie-io/Eppie-App, pull requests merged in 2025-03, with the labels that each got.

#578 fix: MessageReceiver
  src/Eppie.App/Eppie.App.ViewModels/Common/NewMessageData.cs
Labels: platform/all, type/fix

#580 feat: add local ai agents
  src/Eppie.App/Eppie.AI/Service.cs
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.Shared/App.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Services/AIService.cs
  src/Eppie.App/Eppie.App.Shared/Views/IdentityManagerPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/LocalAIAgentSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageControl.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/MessageControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/MessageControl.xaml
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  src/Eppie.App/Eppie.App.UWP/Resources/Strings/en/App.Resources.resw
  src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/IdentityManagerPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/LocalAIAgentSettingsPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MessagePageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/SelectServicePageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Services/IAIService.cs
  src/Eppie.App/Eppie.App/Eppie.App.csproj
  src/Eppie.App/Eppie.App/Resources/Strings/en/App.Resources.resw
Labels: platform/all, type/feature

#581 style: format xaml files
  src/Eppie.App/Eppie.App.Shared/Views/IdentityManagerPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/LocalAIAgentSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SelectServicePage.xaml
Labels: platform/all, type/style

#582 ci: add xaml style check workflow
  .github/workflows/xaml-style-check.yml
Labels: platform/all, type/ci

#585 build: fix macOS
  src/Eppie.App/Eppie.App.Shared/Services/AIService.cs
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  src/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: platform/all, type/fix, type/build

#586 fix: tabview crash on maccatalyst
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MailBoxesListControl.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/NavPanelTabControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/NavPanelTabControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj
Labels: platform/ios, platform/macos, type/fix

#590 ci: fix ios build
  .github/actions/install-prerequisites/action.yml
Labels: platform/ios, type/ci

#593 refactor: clean code
  src/Eppie.App/Eppie.AI/Service.cs
  src/Eppie.App/Eppie.AI/Utils/GenAIModel.cs
  src/Eppie.App/Eppie.App.Shared/Models/NotificationManager.cs
  src/Eppie.App/Eppie.App.Shared/Services/ErrorHandler.cs
  src/Eppie.App/Eppie.App.Shared/Views/BasePage.cs
  src/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/LanguageSelectionControl.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/RichTextEditor.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/BoolToValueConverter.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/TextDocumentExtension.cs
  src/Eppie.App/Eppie.App.UWP/Properties/AssemblyInfo.cs
  src/Eppie.App/Eppie.App.ViewModels/AllMessagesPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/ContactMessagesPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/FolderMessagesPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/IdentityManagerPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/LocalAIAgentSettingsPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MessagePageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Models/MailBoxesModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Services/IDragAndDropService.cs
  src/Eppie.App/Eppie.App/Models/BrandLoader.cs
  src/Eppie.App/Eppie.App/Services/PurchaseService.cs
Labels: platform/all, type/refactor

#595 build: update Uno.Sdk version
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json
  src/Eppie.App/global.json
Labels: type/build, platform/uno

#599 fix: add MessageIsNotExistException
  src/Eppie.App/Eppie.App.Shared/Services/AIService.cs
  src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/SelectServicePageViewModel.cs
Labels: platform/all, type/fix

#601 build: disable Eppie.AI in uno apps
  src/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: type/build, platform/uno

#604 fix: add get message body high priority async
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.Shared/Services/AIService.cs
  src/Eppie.App/Eppie.App.Shared/Views/LocalAIAgentSettingsPage.xaml
  src/Eppie.App/Eppie.App.ViewModels/LocalAIAgentSettingsPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MessagePageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MessagesViewModel.cs
Labels: platform/all, type/fix

#608 fix: fix notification
  src/Eppie.App/Eppie.App.Shared/Models/NotificationManager.cs
Labels: platform/all, type/fix

#610 ci: add publish workflow
  .github/configurations/publish-desktop-binaries.json
  .github/configurations/publish-desktop-span.json
  .github/configurations/publish.json
  .github/workflows/publish-desktop-binaries.yml
  .github/workflows/publish.yml
Labels: platform/desktop, type/ci

#611 fix: fix open default browser
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageControl.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/MessageControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/MessageControl.xaml
Labels: platform/all, type/fix

#617 fix: fix SetClipboardContent
  src/Eppie.App/Eppie.App.Shared/Services/ClipboardProvider.cs
  src/Eppie.App/Eppie.App.Shared/Services/MessageService.cs
  src/Eppie.App/Eppie.App.ViewModels/MessagesViewModel.cs
Labels: platform/all, type/fix

#619 Update README.md
  README.md
Labels: platform/desktop, platform/macos, type/build, type/documentation

#622 fix: fix Expander
  src/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/DecentralizedAccountSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/ProtonAccountSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml
Labels: platform/desktop, type/fix, platform/uno

#620 docs: update README.md
  README.md
Labels: type/documentation, platform/irrelevant

#621 fix: add development support link
  src/Eppie.App/Eppie.App.UWP/Models/BrandLoader.cs
  src/Eppie.App/Eppie.App.ViewModels/AboutPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/AccountSettingsModel.cs
  src/Eppie.App/Eppie.App.ViewModels/AccountSettingsPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/BaseAccountSettingsPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/BaseMessageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Common/NewMessageData.cs
  src/Eppie.App/Eppie.App.ViewModels/Common/SeedWordModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Eppie.App.ViewModels.csproj
  src/Eppie.App/Eppie.App.ViewModels/Extensions/CredentialExtension.cs
  src/Eppie.App/Eppie.App.ViewModels/IdentityManagerPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Items/ContactItem.cs
  src/Eppie.App/Eppie.App.ViewModels/LocalAIAgentSettingsPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MessagesViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/PasswordPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/ProtonAccountSettingsPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Services/IBrandService.cs
  src/Eppie.App/Eppie.App/Models/BrandLoader.cs
Labels: platform/all, type/fix

#623 docs: minor fixes in README.md
  README.md
Labels: type/documentation, platform/irrelevant

#625 ci: publish desktop arm64 binaries
  .github/configurations/publish-desktop-binaries.json
  .github/workflows/publish-desktop-binaries.yml
  .github/workflows/publish.yml
  src/Eppie.App/Directory.Build.targets
Labels: platform/desktop, type/ci

#630 feat: add dutch
  src/Eppie.App/Eppie.App.Resources.Shared/Eppie.App.Resources.Shared.projitems
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/nl/Resources.resw
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/nl/Controls.resw
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  src/Eppie.App/Eppie.App.UWP/Resources/Strings/nl/App.Resources.resw
  src/Eppie.App/Eppie.App/Resources/Strings/nl/App.Resources.resw
Labels: platform/all, type/localization

#632 ci: set package version
  .github/actions/assign-version/action.yml
  .github/configurations/publish-desktop-binaries.json
  .github/workflows/publish-desktop-binaries.yml
  src/Eppie.App/Directory.Build.targets
Labels: platform/all, type/ci

#633 ci: set ApplicationVersion option
  .github/actions/assign-version/action.yml
  .github/workflows/publish-desktop-binaries.yml
Labels: platform/all, type/ci

#629 docs: update README.md
  README.md
Labels: platform/desktop, type/documentation
