Repository Eppie-io/Eppie-App, pull requests merged in 2025-06, with the labels that each got.

#702 feat: hide sensitive information in the log
  src/Eppie.App/Directory.Packages.props
  src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  src/Eppie.App/Eppie.App.Shared/Logging/HashTransformOperator.cs
  src/Eppie.App/Eppie.App.Shared/Logging/LogConfiguration.cs
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  src/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: platform/all, type/feature, ignore-for-release

#703 feat: add exception details to log
  src/Eppie.App/Directory.Packages.props
  src/Eppie.App/Eppie.App.Shared/Logging/LogConfiguration.cs
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  src/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: platform/all, type/feature, ignore-for-release

#707 feat: add open logs folder button
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.Shared/Services/LauncherService.cs
  src/Eppie.App/Eppie.App.Shared/Services/LocalSettingsService.cs
  src/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml
  src/Eppie.App/Eppie.App.ViewModels/Services/ILauncherService.cs
  src/Eppie.App/Eppie.App.ViewModels/Services/ILocalSettingsService.cs
  src/Eppie.App/Eppie.App.ViewModels/SettingsPageViewModel.cs
Labels: platform/all, type/feature

#696 fix: change support development button
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  src/Eppie.App/Eppie.App.Shared/Services/AppStoreService.cs
  src/Eppie.App/Eppie.App.Shared/Services/LocalSettingsService.cs
  src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/SupportDevelopmentControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/SupportDevelopmentControl.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/en/Controls.resw
  src/Eppie.App/Eppie.App.UWP/Services/AppStoreService.cs
  src/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Services/IAppStoreService.cs
  src/Eppie.App/Eppie.App/Services/AppStoreService.cs
Labels: platform/all, type/fix

#717 build: migrating to Uno Platform 6.0
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json
  src/Eppie.App/Eppie.App/Platforms/Desktop/Program.cs
  src/Eppie.App/global.json
Labels: type/build, platform/uno

#721 build: bump uno sdk
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json
  src/Eppie.App/global.json
Labels: type/build, platform/uno

#722 build: update android
  src/Eppie.App/Eppie.App/Platforms/Android/Main.Android.cs
  src/Eppie.App/Eppie.App/Platforms/Android/MainActivity.Android.cs
  src/Eppie.App/Eppie.App/Platforms/Android/Resources/values/Styles.xml
  src/Eppie.App/Eppie.App/Platforms/Android/environment.conf
Labels: platform/android, type/build, platform/uno

#723 build: update wasm
  src/Eppie.App/Eppie.App/Platforms/WebAssembly/Program.cs
Labels: platform/wasm, type/build, platform/uno

#726 feat: add html email display to the desktop app
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/MessageControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj
  src/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: platform/desktop, type/feature

#727 refactor: remove Uno.Toolkit.UI package
  src/Eppie.App/Directory.Packages.props
  src/Eppie.App/Eppie.App.Shared/App.xaml
  src/Eppie.App/Eppie.App.Shared/Views/BasePage.cs
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  src/Eppie.App/Eppie.App.UWP/Models/BrandLoader.cs
  src/Eppie.App/Eppie.App/Eppie.App.csproj
  src/Eppie.App/Eppie.App/Models/BrandLoader.cs
Labels: platform/all, type/refactor

#731 chore: remove webview2 hotfix
  src/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: type/chore, platform/uno

#730 feat: redesign about page
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.Shared/StaticResources/StaticStringResources.xaml
  src/Eppie.App/Eppie.App.Shared/Views/AboutPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/AboutPage.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml
  src/Eppie.App/Eppie.App.UWP/Assets/Svg/github.svg
  src/Eppie.App/Eppie.App.UWP/Assets/Svg/twitter.svg
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  src/Eppie.App/Eppie.App.ViewModels/AboutPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Collections/ContactsSorting/ByTimeContactComparer.cs
  src/Eppie.App/Eppie.App/Assets/Svg/github.svg
  src/Eppie.App/Eppie.App/Assets/Svg/twitter.svg
  src/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: platform/all, type/feature

#732 refactor: change the override of the TargetFrameworks property
  .github/configurations/publish-desktop-app.json
  .github/configurations/publish-desktop-binaries.json
  .github/configurations/publish-desktop-span.json
  src/Eppie.App/Directory.Build.targets
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Eppie.App.UI.Uno.csproj
  src/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: platform/desktop, type/refactor, platform/uno

#734 refactor: change the definition of UnoFeatures
  src/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: type/refactor, platform/uno

#741 fix: fix about page
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.Shared/Views/AboutPage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/WhatsNewControl.xaml
Labels: platform/all, type/fix

#751 fix: fix ApplyCommand
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/DialogBehavior.cs
  src/Eppie.App/Eppie.App.ViewModels/SeedRestorePageViewModel.cs
Labels: platform/all, type/fix

#754 chore: add permission internet
  src/Eppie.App/Eppie.App/Eppie.App.csproj
  src/Eppie.App/Eppie.App/Platforms/Android/AndroidManifest.xml
Labels: platform/android, type/chore

#755 fix: fix zh
  src/Eppie.App/Eppie.App.Resources.Shared/Eppie.App.Resources.Shared.projitems
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/zh-Hans/Resources.resw
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/zh-Hans/Controls.resw
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  src/Eppie.App/Eppie.App.UWP/Resources/Strings/zh-Hans/App.Resources.resw
  src/Eppie.App/Eppie.App/Resources/Strings/zh-Hans/App.Resources.resw
  src/Eppie.App/Eppie.App/appsettings.json
Labels: platform/all, type/localization

#758 chore: fix AndroidKeyStore
  src/Eppie.App/Eppie.App/Eppie.App.csproj
Labels: platform/android, type/chore
