Repository Eppie-io/Eppie-App, pull requests merged in 2025-04, with the labels that each got.

#642 ci: refactor publish scripts
  .github/configurations/publish-desktop-binaries.json
  .github/configurations/publish-desktop-span.json
  .github/configurations/publish-mac-catalyst-pkg.json
  .github/workflows/publish-desktop-binaries.yml
  .github/workflows/publish-desktop-snap.yml
  .github/workflows/publish-mac-catalyst-pkg.yml
  .github/workflows/publish.yml
  src/Eppie.App/Directory.Build.targets
Labels: platform/all, type/ci

#643 ci: change version format
  .github/actions/assign-version/action.yml
Labels: platform/all, type/ci

#646 docs: add asset links to readme
  README.md
Labels: type/documentation, platform/irrelevant

#649 build(deps): Bump to M.E.AI 9.4.0-preview.1.25207.5
  src/Eppie.App/Directory.Packages.props
  src/Eppie.App/Eppie.AI/Service.cs
  src/Eppie.App/Eppie.AI/Utils/GenAIModel.cs
Labels: platform/all, type/build

#650 fix: changes in message handling and interface
  src/Eppie.App/Eppie.App.Shared/Services/AIService.cs
  src/Eppie.App/Eppie.App.Shared/Views/LocalAIAgentSettingsPage.xaml
Labels: platform/all, type/fix

#658 ci: update workflows
  .github/actions/assign-version/action.yml
  .github/actions/install-prerequisites/action.yml
  .github/configurations/build.json
  .github/configurations/publish-desktop-app.json
  .github/configurations/publish-mac-catalyst-pkg.json
  .github/workflows/build.yml
  .github/workflows/publish-desktop-app.yml
  .github/workflows/publish-desktop-binaries.yml
  .github/workflows/publish-desktop-snap.yml
  .github/workflows/publish-mac-catalyst-pkg.yml
  .github/workflows/publish.yml
Labels: platform/all, type/ci

#659 ci: add publish win-arm64
  .github/configurations/publish-desktop-binaries.json
Labels: platform/desktop, type/ci

#660 ci: change artifact name
  .github/actions/assign-version/action.yml
  .github/workflows/publish-desktop-app.yml
  .github/workflows/publish-desktop-binaries.yml
  .github/workflows/publish-desktop-snap.yml
  .github/workflows/publish-mac-catalyst-pkg.yml
Labels: platform/all, type/ci
