Repository Eppie-io/Eppie-App, pull requests merged in 2025-09, with the labels that each got.

#822 fix: fix resource string
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/en/Controls.resw
Labels: platform/all, type/fix

#824 fix: fix account update
  src/Eppie.App/Eppie.App.ViewModels/DecentralizedAccountSettingsPageViewModel.cs
Labels: platform/all, type/fix

#835 feat: add account settings modes
  src/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NewAccountSettingsControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NewAccountSettingsControl.xaml.cs
  src/Eppie.App/Eppie.App.ViewModels/AccountSettingsPageViewModel.cs
Labels: platform/all, type/feature

#853 refactor: email settings control
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AccountSettingsControl.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NewAccountSettingsControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/NewAccountSettingsControl.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Resources/Strings/en/Controls.resw
Labels: platform/all, type/refactor, ignore-for-release

#851 feat: new settings page
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml
  src/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs
Labels: platform/all, type/feature

#864 refactor: enhance brand data management and bindings
  src/Eppie.App/Eppie.App.Shared/StaticResources/BrandResource.cs
  src/Eppie.App/Eppie.App.Shared/Views/AboutPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/BasePage.cs
  src/Eppie.App/Eppie.App.Shared/Views/PasswordPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/WelcomePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/WelcomePage.xaml.cs
  src/Eppie.App/Eppie.App.UWP/Models/BrandLoader.cs
  src/Eppie.App/Eppie.App.ViewModels/AboutPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Services/IBrandService.cs
  src/Eppie.App/Eppie.App/Models/BrandLoader.cs
Labels: platform/all, type/refactor

#872 feat: add address control
  src/Eppie.App/Eppie.App.Shared/Views/BitcoinAddressSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/EppieAddressSettingsPage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressControl.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressSettingsView.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailSettingsControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
Labels: platform/all, type/feature, ignore-for-release

#874 feat: make ethereum address settings
  src/Eppie.App/Eppie.App.Shared/Views/DecentralizedAddressSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/DecentralizedAddressSettingsPage.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Views/EthereumAddressSettingsPage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/DecentralizedAccountSettingsControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/DecentralizedAccountSettingsControl.xaml.cs
  src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/DecentralizedAddressSettingsPageViewModel.cs
Labels: platform/all, type/feature, ignore-for-release

#877 fix: `BrandLoader` key inconsistency causing GetGitHub() to fail
  src/Eppie.App/Eppie.App/Models/BrandLoader.cs
Labels: platform/all, type/fix

#879 fix: correct the merge
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
Labels: platform/all, type/fix, ignore-for-release

#880 refactor: add content property
  src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/BitcoinAddressSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/EmailAddressSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/EppieAddressSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/EthereumAddressSettingsPage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressControl.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AddressSettingsView.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/AdvancedSettingsControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailSettingsControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/OptionControl.xaml.cs
Labels: platform/all, type/refactor

#885 chore: replace hardcoded seed phrase text with "Not implemented"
  src/Eppie.App/Eppie.App.Shared/Views/AppSettingsPage.xaml
Labels: platform/all, type/chore
