Repository Eppie-io/Eppie-App, pull requests merged in 2025-08, with the labels that each got.

#794 fix: standard address
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EmailsInputControl.xaml.cs
  src/Eppie.App/Eppie.App.ViewModels/NewMessagePageViewModel.cs
Labels: platform/all, type/fix

#798 refactor: refactor message deletion logic in MessagesViewModel
  src/Eppie.App/Eppie.App.ViewModels/MessagesViewModel.cs
Labels: platform/all, type/fix

#804 refactor: AI service handling
  src/Eppie.App/Eppie.App.Shared/Views/BasePage.cs
  src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs
Labels: platform/all, type/refactor

#807 Add GitHub release downloads badge
  README.md
Labels: type/chore, platform/irrelevant

#809 build: bump Uno.Sdk to 6.2.29
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/global.json
  src/Eppie.App/global.json
Labels: type/build, platform/uno

#810 feat: configure minimum window size
  src/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs
  src/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs
  src/Eppie.App/Eppie.App.Shared/App.xaml.cs
Labels: platform/all, type/feature
