Repository Eppie-io/Eppie-App, pull requests merged in 2025-02, with the labels that each got.

#528 feat: add EditMessageControl to winui
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/RichTextEditor.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/TextDocumentExtension.UWP.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/TextDocumentExtension.Uno.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/TextDocumentExtension.Win.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/TextDocumentExtension.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/EditMessageControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/EditMessageControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/MessageControl.xaml.cs
Labels: platform/uwp, platform/winui, type/feature

#532 fix: unread badge
  src/Eppie.App/Eppie.App.Shared/Models/NotificationManager.cs
Labels: kind/enhancement, platform/all

#538 fix: escape angle brackets
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/TextDocumentExtension.cs
Labels: platform/all, type/fix

#537 fix: prepare for store distribution
  src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  src/Eppie.App/Eppie.App.ViewModels/MessagePageViewModel.cs
  src/Eppie.App/Eppie.App/Authorization/AuthConfig.Win.cs
  src/Eppie.App/Eppie.App/Package.appxmanifest
Labels: platform/winui, type/fix

#540 fix: save emails filter
  src/Eppie.App/Eppie.App.Shared/Services/LocalSettingsService.cs
  src/Eppie.App/Eppie.App.Shared/Views/AllMessagesPage.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Views/ContactMessagesPage.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Views/FolderMessagesPage.xaml.cs
  src/Eppie.App/Eppie.App.ViewModels/AllMessagesPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/ContactMessagesPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/FolderMessagesPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MessagesViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Services/ILocalSettingsService.cs
Labels: platform/all, type/fix

#542 fix: set XamlRoot before showing ContentDialog
  src/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs
  src/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs
  src/Eppie.App/Eppie.App.Shared/App.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Services/MessageService.cs
  src/Eppie.App/Eppie.App.Shared/Views/BasePage.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Tools/UITools.cs
Labels: platform/all, type/fix, area/ui

#544 fix: remove old webview
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageControl.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/MessageControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/MessageControl.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Eppie.App.UI.UWP.csproj
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/MessageControl.xaml.cs
Labels: platform/all, type/fix

#536 Update README.md
  README.md
Labels: kind/documentation, platform/all, area/docs

#547 fix: update accounts
  src/Eppie.App/Eppie.App.Shared/Services/MessageService.cs
  src/Eppie.App/Eppie.App.ViewModels/AccountSettingsPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/IdentityManagerPageViewModel.cs
Labels: platform/all, type/fix

#548 fix: GetHtml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/RichTextEditor.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Extensions/TextDocumentExtension.cs
  src/Eppie.App/Eppie.App.ViewModels/Common/NewMessageData.cs
Labels: platform/all, type/fix

#550 fix: tooltip string resources
  src/Eppie.App/Eppie.App.Resources.Shared/Eppie.App.Resources.Shared.projitems
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/af/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/ar/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/be/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/ca/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/cs/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/da/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/de/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/el/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/es/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/et/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/fi/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/fr/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/he/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/hu/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/it/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/ja/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/ko/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/lv/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/nl/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/no/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/pl/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/pt-BR/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/pt/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/ro/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/ru/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/sr-Cyrl/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/sv/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/tr/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/uk/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/vi/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/zh-CN/Resources.resw
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/zh-TW/Resources.resw
  src/Eppie.App/Eppie.App.Shared/Views/AllMessagesPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/ContactMessagesPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/FolderMessagesPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  src/Eppie.App/Eppie.App.UWP/Package.appxmanifest
  src/Eppie.App/Eppie.App.UWP/Resources/Strings/en/App.Resources.resw
  src/Eppie.App/Eppie.App.UWP/Resources/Strings/pl/App.Resources.resw
  src/Eppie.App/Eppie.App.UWP/Resources/Strings/ru/App.Resources.resw
  src/Eppie.App/Eppie.App.UWP/Resources/Strings/zh-CN/App.Resources.resw
  src/Eppie.App/Eppie.App/Resources/Strings/en/App.Resources.resw
  src/Eppie.App/Eppie.App/Resources/Strings/pl/App.Resources.resw
  src/Eppie.App/Eppie.App/Resources/Strings/ru/App.Resources.resw
  src/Eppie.App/Eppie.App/Resources/Strings/zh-CN/App.Resources.resw
Labels: platform/all, type/fix

#555 feat: add deafult auth config
  src/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.Uno.cs
Labels: type/feature, ignore-for-release, platform/uno

#556 ci: publish macos workflow
  .github/workflows/publish-macos.yml
Labels: platform/macos, type/ci

#557 fix(ui): fix EditMessageControl properties
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/EditMessageControl.xaml.cs
Labels: platform/all, type/fix

#564 feat(ui): add ui behavior
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/CommandArgumentBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
Labels: platform/all, type/feature, ignore-for-release, area/ui

#565 refactor: rename namespace
  src/Eppie.App/Eppie.App.Shared/Services/StorageItemsService.cs
  src/Eppie.App/Eppie.App.Shared/Views/AccountSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/DecentralizedAccountSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/IdentityManagerPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/PasswordPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/PgpKeyPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/PgpKeysPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/ProtonAccountSettingsPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SelectEmailProviderPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/ClipboardBehaviorBase.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/CopyToClipboardBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/DialogBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/FileBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/ItemClickCommandBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/ListViewItemClickBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/ObjectToFileBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/PasteFromClipboardBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/TreeViewItemInvokeBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/ContactsListControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MailBoxesListControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageListControl.xaml
Labels: platform/all, type/refactor

#559 feat: add local AI
  .gitignore
  src/Eppie.App/Directory.Packages.props
  src/Eppie.App/Eppie.AI/Eppie.AI.csproj
  src/Eppie.App/Eppie.AI/Service.cs
  src/Eppie.App/Eppie.AI/Utils/GenAIModel.cs
  src/Eppie.App/Eppie.AI/Utils/HardwareAccelerator.cs
  src/Eppie.App/Eppie.AI/Utils/LlmPromptTemplate.cs
  src/Eppie.App/Eppie.App.Resources.Shared/Strings/en/Resources.resw
  src/Eppie.App/Eppie.App.Shared/App.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  src/Eppie.App/Eppie.App.Shared/Services/AIService.cs
  src/Eppie.App/Eppie.App.Shared/Views/BasePage.cs
  src/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageControl.xaml.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/MessageControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/MessageControl.xaml
  src/Eppie.App/Eppie.App.UWP/Eppie.App.UWP.csproj
  src/Eppie.App/Eppie.App.UWP/Resources/Strings/en/App.Resources.resw
  src/Eppie.App/Eppie.App.ViewModels/BaseViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MainPageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/MessagePageViewModel.cs
  src/Eppie.App/Eppie.App.ViewModels/Services/IAIService.cs
  src/Eppie.App/Eppie.App.ViewModels/SettingsPageViewModel.cs
  src/Eppie.App/Eppie.App.sln
  src/Eppie.App/Eppie.App/Eppie.App.csproj
  src/Eppie.App/Eppie.App/Resources/Strings/en/App.Resources.resw
Labels: platform/all, type/feature

#569 refactor: behaviors
  src/Eppie.App/Eppie.App.Shared/App.xaml
  src/Eppie.App/Eppie.App.Shared/Converters/AttachmentConverter.cs
  src/Eppie.App/Eppie.App.Shared/Eppie.App.Shared.projitems
  src/Eppie.App/Eppie.App.Shared/StaticResources/StaticResources.xaml
  src/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/PgpKeyPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/PgpKeysPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SeedGeneratePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SeedRestorePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/SettingsPage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/ClipboardBehaviorBase.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/CommandArgumentBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/CopyToClipboardBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/FileBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/ItemClickCommandBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/ObjectToFileBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Behaviors/PasteFromClipboardBehavior.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Converters/JoinConverter.cs
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Eppie.App.UI.Shared.projitems
  src/Eppie.App/Eppie.App.ViewModels/BaseMessageViewModel.cs
Labels: platform/all, type/refactor

#571 fix: item picker winui
  src/Eppie.App/Eppie.App.Shared/App.UWP.xaml.cs
  src/Eppie.App/Eppie.App.Shared/App.Uno.xaml.cs
  src/Eppie.App/Eppie.App.Shared/App.xaml.cs
  src/Eppie.App/Eppie.App.Shared/Services/AIService.cs
  src/Eppie.App/Eppie.App.Shared/Services/FileOperationProvider.cs
  src/Eppie.App/Eppie.App.Shared/Views/MainPage.xaml.cs
Labels: platform/all, type/fix

#574 style: format xaml files
  src/Eppie.App/Eppie.App.Shared/Views/AllMessagesPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/ContactMessagesPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/FolderMessagesPage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/MessagePage.xaml
  src/Eppie.App/Eppie.App.Shared/Views/NewMessagePage.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MailBoxesListControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Shared/Controls/MessageListControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.UWP/Controls/MessageControl.xaml
  src/Eppie.App/Eppie.App.UI/Eppie.App.UI.Uno/Controls/MessageControl.xaml
Labels: platform/all, type/style, ignore-for-release
